pages/checkoutPage/routes.py
from flask import Blueprint
from flask import render_template, Flask, request, url_for, redirect, session,jsonify
from forms import *
from features import *
from datetime import datetime, timedelta,date
import sqlite3

checkOutPage= Blueprint("itemCheckOut", __name__)

@checkOutPage.route('/itemCheckOut/<int:item>',methods=('GET','Post'))
def itemCheckOut(item):
    searchForm=SearchForm()
    logoutForm=LogoutForm()
    checkoutForm=CheckoutForm()
    name=session.get('username')
    if(checkoutForm.returnItem.data):
        if(name == None):
            return redirect(url_for('login'))
        conn=sqlite3.connect("library.db")
        conn.row_factory=sqlite3.Row
        query=checkItemCheckout(item,session.get('user_id'))
        checkedOut=conn.execute(query).fetchone()
        query="DELETE FROM Borrowing_History WHERE borrowingID = ?"
        data=[checkedOut['BorrowingID']]
        conn.execute(query,data)
        query=f"SELECT * FROM ITEMAVAILABILITY WHERE AVAILABILITY_ID={item}"
        available=conn.execute(query).fetchone()
        query=F"UPDATE ItemAvailability SET available_copies = ? WHERE AVAILABILITY_ID={item}"
        if(int(available['available_copies'])<int(available['item_totalNo'])):
            data=[available['available_copies']+1]
            conn.execute(query,data)
        
        conn.commit()
        conn.close()

    elif(checkoutForm.renew.data):
        if(name == None):
            return redirect(url_for('login'))
        conn=sqlite3.connect("library.db")
        conn.row_factory=sqlite3.Row
        
        today=datetime.now().date()
        retDate=today+timedelta(weeks=2)
        query=checkItemCheckout(item,session.get('user_id'))
        checkedOut=conn.execute(query).fetchone()
        query=f"select * from renewals where borrowingID={checkedOut['BorrowingID']}"
        checkedOut=len(conn.execute(query).fetchall())
        if(len==0):
            query="INSERT INTO Renewals('BorrowingID', 'Renewal_status', 'Renewal_date', 'Renewal_reason') VALUES (?,?,?,?)"
            data=[checkedOut['BorrowingID'],'Pending',today,checkoutForm.renewReason.data]
            conn.execute(query,data)
            print('done')
        conn.commit()
        conn.close()
        print("no renew")
        


    elif(checkoutForm.submit_button.data):
        conn=sqlite3.connect("library.db")
        conn.row_factory=sqlite3.Row
        query=checkOutItem()
        today=datetime.now().date()
        retDate=today+timedelta(weeks=2)
        data=[session.get('user_id'),item,today,retDate]
        conn.execute(query,data)
        query=f"SELECT * FROM ITEMAVAILABILITY WHERE AVAILABILITY_ID={item}"
        available=conn.execute(query).fetchone()
        query=F"UPDATE ItemAvailability SET available_copies = ? WHERE AVAILABILITY_ID={item}"
        data=[int(available['available_copies'])-1]
        conn.execute(query,data)
        conn.commit()
        conn.close()

    
    if (logoutForm.logout_button.data):
        session['user_id']=None
        session['username']=None

    if (searchForm.search_button.data):
        search=request.form['search_bar']
        return redirect(url_for('Search.search',search=search))
    
    checkedOut=0
    conn=sqlite3.connect("library.db")
    conn.row_factory=sqlite3.Row
    query=itemData(item)
    search_results=conn.execute(query).fetchone()
    if(session.get('user_id')!=None):
        query=checkItemCheckout(item,session.get('user_id'))
        checkedOut=len(conn.execute(query).fetchall())
    conn.close()
    
    return render_template('item.html',name=name,logoutForm=logoutForm, searchForm=searchForm, search_result=search_results, checkoutForm=checkoutForm, checkedOut=checkedOut)

pages/eventRegPage/routes.py
from flask import Blueprint
from flask import render_template, Flask, request, url_for, redirect, session,jsonify
from forms import *
from features import *
from datetime import datetime, timedelta,date
import sqlite3

eventsRegPage= Blueprint("eventRegister", __name__)

@eventsRegPage.route('/eventRegister<int:eventID>',methods=('GET','Post'))
def eventRegister(eventID):
    searchForm=SearchForm()
    logoutForm=LogoutForm()
    submit=Register()
    name=session.get('username')
    if(submit.unregister_button.data):
        conn=sqlite3.connect("library.db")
        conn.row_factory=sqlite3.Row
        query="DELETE FROM EVENTREGISTRATION WHERE eventID = ? AND userID = ?"
        data=[eventID,session.get('user_id')]
        conn.execute(query,data)
        conn.commit()
        conn.close()
    if(submit.submit_button.data):
        conn=sqlite3.connect("library.db")
        conn.row_factory=sqlite3.Row
        query="INSERT INTO EVENTREGISTRATION('EventID', 'UserID', 'ERegistration_date') VALUES (?,?,?)"
        data=[eventID,session.get('user_id'),datetime.now().date()]
        conn.execute(query,data)
        conn.commit()
        conn.close()

    if (logoutForm.logout_button.data):
        session['user_id']=None
        session['username']=None
    if (searchForm.search_button.data):
        search=request.form['search_bar']
        
        return redirect(url_for('Search.search',search=search))
    
    conn=sqlite3.connect("library.db")
    conn.row_factory=sqlite3.Row
    query=eventQuery(eventID)
    event=conn.execute(query).fetchone()
    query=query=f'''SELECT * FROM EVENTREGISTRATION 
    left join events on eventregistration.eventID=events.eventid
    where USERid={session['user_id']} and eventregistration.eventID={eventID}'''
    registeredEvents=conn.execute(query).fetchall()
    conn.close()
    return render_template('event.html',name=name,logoutForm=logoutForm, searchForm=searchForm, title=eventID, event=event, submit=submit,registered=(len(registeredEvents))>0)

templates/askUs.html
{% extends "top.html" %}

{% block content %}
    <h1>Contact Us</h1>
    <p>Email: info@library.com</p>
    <p>Phone:  012-345-6789</p>
{% endblock %}

templates/blank.html
{% extends "top.html" %}

{% block content %}

<p>Thanks for {{string}}</p>

{% endblock %}

templates/donate.html
{% extends "top.html" %}

{% block content %}
    <h1>Donate</h1>
    <form action="" method="post" novalidate>
        
        <p>{{donateForm.dropdown.label}}: {{donateForm.dropdown}}</p>
        <p>{{donateForm.title.label}}: {{donateForm.title}}</p>
        <p>{{donateForm.description.label}}: {{donateForm.description}}</p>
        <p>Donate Date: {{donateForm.donateDate}}</p>
        <p>{{donateForm.submit_button.label}}: {{donateForm.submit_button}}</p>
        
        
    </form>
    
{% endblock %}

templates/event.html
{% extends "top.html" %}

{% block content %}
    <h1>Events Registered For</h1>
    <div class=events>
        <h2>{{ event['Event_name']}}</h2>
        <p>{{ event['Event_date']}}</p>
    </div>
    <p>reccommended for: {{ event['Audience']}}</p><br>
    <p>Room Number: {{ event['Venue']}}</p><br>
    <p>{{ event['Event_description']}}</p><br>
    <p>max attendence: {{ event['Event_capacity']}}</p><br>
    <form method="POST">
        {% if registered %}
        {{submit.unregister_button}}
        {% else %}
        {{submit.submit_button}}
        {% endif %}
    </form>
{% endblock %}

templates/eventList.html
{% extends "top.html" %}

{% block content %}
    <h1>Events</h1>
    {% for event in eventsList %}
        <div class='events'>
            <div class=events>
                <a href="{{url_for('eventRegister.eventRegister',eventID=event['EventID'])}}">{{ event['event_name']}}</a>
                <p>Date: {{ event['event_date']}}</p>
            </div>

        </div>
    {% endfor %}
{% endblock %}

templates/item.html
{% extends "top.html" %}

{% block content %}

    {% if search_result['item_type'] == "Book"%}
    <div>
        <H2>{{ search_result['Book_title']}}</H2>
        <p>Author: {{ search_result['Book_author'] }}</p> <br>
        <p>Year Published: {{ search_result['Book_publication_yr'] }}</p> <br>
        <p>Description: {{ search_result['Book_description'] }}</p> <br>

    </div>
    {%endif%}
    
    {% if search_result['item_type'] == "Magazine"%}
    <div>
        <H2>{{ search_result['Magazine_title']}} </H2>
        <p>Publisher: {{ search_result['Magazine_publisher']}}</p><br>
        <p>Issue No: {{ search_result['Magazine_issueNo']}}</p>
    </div>
    {%endif%}
    
    {% if search_result['item_type'] == "CD"%}
    <div>
        <H2>{{ search_result['CD_title']}} </H2>
        <p>Artist: {{ search_result['CD_artist']}}</p><br>
        <p>Release Year: {{ search_result['CD_releaseYr']}}</p><br>
        <p>Publisher: {{ search_result['CD_publisher']}}</p><br>
        <p>Number of Tracks: {{ search_result['CD_totalTracks']}}</p><br>
    </div>
    {%endif%}
    
    {% if search_result['item_type'] == "Record"%}
    <div>
        <H2>{{ search_result['Record_title']}} </H2>
        <p>Artist: {{ search_result['Record_artist']}} </p><br>
        <p>Release Year: {{ search_result['Record_releaseYr']}} </p><br>
        <p>Publisher: {{ search_result['Record_publisher']}} </p><br>
        <p>Number of Tracks: {{ search_result['Record_totalTracks']}} </p><br>
    </div>
    {%endif%}
    
    {% if search_result['item_type'] == "Journal"%}
    <div>
        <H2>{{ search_result['Journal_title']}} </H2>
        <p>Publisher: {{ search_result['Journal_publisher']}}</p><br>
        <p>Date Published: {{ search_result['Journal_date']}}</p>
    </div>
    {%endif%}
    
    {% if search_result['item_type'] == "Movie"%}
    <div>
        <H2>{{ search_result['Movie_title']}} </H2>
        <p>Director: {{ search_result['Movie_director']}}</p><br>
        <p>Release Year: {{ search_result['Movie_releaseYr']}}</p><br>
        <p>Movie Cast: {{ search_result['Movie_cast']}}</p><br>
        <p>Movie Time: {{ search_result['Movie_time']}}</p><br>
        <p>Description: {{ search_result['Movie_description']}}</p><br>
    </div>
    {%endif%}
    
    <form method="POST">
        <!--block renewal if item has fines-->
        {% if checkedOut >0 %}
        <h4>Renew</h4>
        <p>Renew Reason: {{checkoutForm.renewReason}}</p><br>
        {{checkoutForm.renew}}
        <h4>return</h4>
        {{checkoutForm.returnItem}}

        {% elif search_result['Available_copies'] > 0%}
        {{checkoutForm.submit_button}}
        
        {% else %}
        {{checkoutForm.submit_button(disabled=disabled)}}<br>
        <p>All of these items are checkout out</p>
        {%endif%}
    </form>


{% endblock %}

templates/login.html
{% extends "top.html" %}

{% block content %}
    <h1>Sign In</h1>
    <form action="" method="post" novalidate>
        {{ loginForm.hidden_tag() }}
        <p>
        {{loginForm.number.label}}<br>
        {{loginForm.number}}
        {% if incorrect %}
        <span style="color:red;">Invalid username or password</span>
        {% endif %}
        </p>
        <p>
        {{loginForm.password.label}}<br>
        {{loginForm.password}}
        </p>
        {{loginForm.submit()}}

    </form>
{% endblock %}

templates/myEvents.html
{% extends "top.html" %}

{% block content %}
<h1>Events registered to</h1>
{% for event in events %}
<div class='events'>
    <div class=events>
        <a href="{{url_for('eventRegister.eventRegister',eventID=event['EventID'])}}">{{ event['event_name']}}</a>
        <p>{{ event['event_date']}}</p>
    </div>
</div>
{% endfor %}
{% endblock %}

templates/myItems.html
{% extends "top.html" %}

{% block content %}
    <p>Your checked out items {{search}}</p>
    {% for search_result in search_results %}
        <div class='search-Result'>
            {% if search_result['item_type'] == "Book"%}
            <div>
                <a href="{{url_for('itemCheckOut.itemCheckOut',item=search_result['item_id'])}}">{{ search_result['Book_title']}} </a>
                {{ search_result['Book_author'] }} <br>
                <p>{{ search_result['return_date']}}</p>
                <p>Fines: {{ search_result['fine_amount']}}</p>
            </div>
            {%endif%}
        
            {% if search_result['item_type'] == "Magazine"%}
            <div>
                <a href="{{url_for('itemCheckOut.itemCheckOut',item=search_result['item_id'])}}">{{ search_result['Magazine_title']}} </a>
                {{ search_result['Magazine_publisher']}}
                <p>{{ search_result['return_date']}}</p>
                <p>Fines: {{ search_result['fine_amount']}}</p>
            </div>
            {%endif%}
        
            {% if search_result['item_type'] == "CD"%}
            <div>
                <a href="{{url_for('itemCheckOut.itemCheckOut',item=search_result['item_id'])}}">{{ search_result['CD_title']}} </a>
                {{ search_result['CD_artist']}}
                <p>{{ search_result['return_date']}}</p>
                <p>Fines: {{ search_result['fine_amount']}}</p>
            </div>
            {%endif%}
        
            {% if search_result['item_type'] == "Record"%}
            <div>
                <a href="{{url_for('itemCheckOut.itemCheckOut',item=search_result['item_id'])}}">{{ search_result['Record_title']}} </a>
                {{ search_result['Record_artist']}}
                <p>{{ search_result['return_date']}}</p>
                <p>Fines: {{ search_result['fine_amount']}}</p>
            </div>
            {%endif%}
        
            {% if search_result['item_type'] == "Journal"%}
            <div>
                <a href="{{url_for('itemCheckOut.itemCheckOut',item=search_result['item_id'])}}">{{ search_result['Journal_title']}} </a>
                {{ search_result['Journal_publisher']}}
                <p>{{ search_result['return_date']}}</p>
                <p>Fines: {{ search_result['fine_amount']}}</p>
            </div>
            {%endif%}
        
            {% if search_result['item_type'] == "Movie"%}
            <div>
                <a href="{{url_for('itemCheckOut.itemCheckOut',item=search_result['item_id'])}}">{{ search_result['Movie_title']}} </a>
                {{ search_result['Movie_director']}}
                <p>{{ search_result['return_date']}}</p>
                <p>Fines: {{ search_result['fine_amount']}}</p>
            </div>
            {%endif%}
            
        </div>
    {% endfor %}
{% endblock %}

templates/search.html
{% extends "top.html" %}

{% block content %}
    {% if search %}
    <p>Search Results for {{search}}</p>
    {% else %}
    <p>Your checked out items </p>
    {% endif %}
    
    {% for search_result in search_results %}
    
    {% if search_result['item_type'] == "Book"%}
    <div>
        <a href="{{url_for('itemCheckOut.itemCheckOut',item=search_result['item_id'])}}">{{ search_result['Book_title']}}</a>
        {{ search_result['Book_author'] }} <br>
    </div>
    {%endif%}

    {% if search_result['item_type'] == "Magazine"%}
    <div>
        <a href="{{url_for('itemCheckOut.itemCheckOut',item=search_result['item_id'])}}">{{ search_result['Magazine_title']}} </a>
        {{ search_result['Magazine_publisher']}}
    </div>
    {%endif%}

    {% if search_result['item_type'] == "CD"%}
    <div>
        <a href="{{url_for('itemCheckOut.itemCheckOut',item=search_result['item_id'])}}">{{ search_result['CD_title']}} </a>
        {{ search_result['CD_artist']}}
    </div>
    {%endif%}

    {% if search_result['item_type'] == "Record"%}
    <div>
        <a href="{{url_for('itemCheckOut.itemCheckOut',item=search_result['item_id'])}}">{{ search_result['Record_title']}} </a>
        {{ search_result['Record_artist']}}
    </div>
    {%endif%}

    {% if search_result['item_type'] == "Journal"%}
    <div>
        <a href="{{url_for('itemCheckOut.itemCheckOut',item=search_result['item_id'])}}">{{ search_result['Journal_title']}} </a>
        {{ search_result['Journal_publisher']}}
    </div>
    {%endif%}

    {% if search_result['item_type'] == "Movie"%}
    <div>
        <a href="{{url_for('itemCheckOut.itemCheckOut',item=search_result['item_id'])}}">{{ search_result['Movie_title']}} </a>
        {{ search_result['Movie_director']}}
    </div>
    {%endif%}
    {% endfor %}

{% endblock %}

templates/top.html
<!doctype html>
<html>
    <head>
        <link rel="stylesheet" type="text/css" href="{{url_for('static',filename='styles/general.css')}}"/>
        {% if title %}
        <title>{{ title }} - library</title>
        {% else %}
        <title>Home</title>
        {% endif %}
    </head>
    <body>
        <div class="very-top">
            <img src="{{url_for('static',filename='logo.jpg')}}" alt="HTML5 Icon" width="60" height="60"/>
            <form action="" method="post" novalidate>
                {{ searchForm.hidden_tag() }}
                {{searchForm.search_bar}}
                {{searchForm.search_button}}
            </form>
            {% if name is not none %}
                <p>Welcome, {{name}}</p><br>
                <form action="" method="post" novalidate>
                    {{logoutForm.logout_button}}
                </form>
            {% else %}
                <a href=http://localhost:5000/login>
                    <button>Login</button>
                    
                </a>
            {% endif %}
        </div>
        <hr>
        <div class="main-menu" style="width: 100%">
            <a href=http://localhost:5000>
                <button style="Width:14.2%">Home</button>
            </a>
            <a href=http://localhost:5000/myItems>
                <button style="Width:14.2%">My Items</button>
            </a>
            <a href=http://localhost:5000/donate>
                <button style="Width:14.2%">Donate</button>
            </a>
            <a href=http://localhost:5000/events>
                <button style="Width:14.2%">Events</button>
            </a>
            <a href=http://localhost:5000/myEvents>
                <button style="Width:14.2%">My Events</button>
            </a>
            <a href=http://localhost:5000/volunteer>
                <button style="Width:14.2%">Volunteer</button>
            </a>
            <a href=http://localhost:5000/askUs>
                <button style="Width:14.2%">Ask Us</button>
            </a>
        </div>

        <hr>

        {% block content %}{% endblock %}
    </body>
</html>

templates/volunteer.html
{% extends "top.html" %}

{% block content %}
    <h1>Volunteer</h1>
    {% if inTable == 0 %}
    <form action="" method="post" novalidate>]
        <div><p>Please describe your availability:</p>{{volunteer.availability}}</div>
        <div><p>Please describe what you want to volunteer for:</p>{{volunteer.interests}}</div>
        <div><p>Please describe what your experience in these interests:</p>{{volunteer.experience}}</div>
        <div>Start date:{{volunteer.startDate}}</div><br>
        <div>End date:{{volunteer.endDate}}</div><br>

        <div>{{volunteer.submit_button()}}</div>
        
    </form>
    {% else %}
    <p>Already registrered to volunteer</p>
    <form method="post">
        <div>{{volunteer.unregister_button()}}</div>
    </form>
    {% endif %}
{% endblock %}